name: dartcade
version: 0.0.2
author: Manuel Ceron <ceronman@gmail.com>
description: |-
  Dartcade is a framework for HTML5 2D game development using Dart.

  Still in a very early stage of development.
homepage: https://github.com/ceronman/dartcade
dependencies:
  browser: '>=0.10.0 <0.11.0'
  vector_math: '>=1.4.3 <1.5.0'
